#!/usr/bin/env python
# coding: utf-8

# In[5]:


class HausaStemmer:
    def __init__(self):
        # Define a list of stopwords
        self.stopwords = ['a', 'amma', 'ba', 'ban', 'ce', 'cikin', 'da', 'don', 'ga', 'in', 'ina', 'ita', 'ji', 'ka', 'ko', 'kuma', 'lokacin', 'ma', 'mai', 'na', 'ne', 'ni', 'sai', 'shi', 'su', 'suka', 'sun', 'ta', 'tafi', 'take', 'tana', 'wani', 'wannan', 'wata', 'ya', 'yake', 'yana', 'yi', 'za','inya']
        
        # Define a dictionary of common words (you can expand this)
        self.dictionary = {
            'murhu': 'murh',
            'murahu': 'murh',
            'karya':'kary',
            'karnuka':'karn',
            'karnukan':'karn',
            'sarki':'sark',
            'sarakai':'sarak',
            'manazarci':'manazar',
            'masunci':'sunc',
            'masunciya':'sunc',
            'bakano':'kan',
            'bakaniya':'kan',
            'baduddire':'gudd',
            'gidaje':'gid',
            'bishiya':'bish',
            'bishiyoyi':'bishiy',
            'falake':'falk',
            'rumfuna':'runf',
            'benenaye':'benen',
            'rafuna':'raf',
            'dakuna':'dak',
            'Dalibai':'dalib',
            'dalibi':'dalib',
            'daliba':'dalib',
            'yara':'yar',
            'yarinya':'yar',
            'mabuɗi': 'buɗ',
            'mayanka':'yank',
            'mawaƙi':'waƙ',
            'banufiya':'nufiy',
            'bakatsine':'katsin',
            'gurgu':'gurg',
            'guragu':'gurag',
            'gurguwa':'gurag',
            'kurame':'kuram',
            'birane':'biran',
            'barade':'bard',
            'dokuna':'dokun',
            'doki':'dok',
            'dokin':'dok',
            'riga':'rig',
            'wando':'wand',
            'hula':'hul',
            'karfe':'karf',
            'tasa':'tas',
            'wuta':'wut',
            'takalmi':'takalm',
            'jaka':'jak',
            'alkalami':'alkalam',
            'takadda':'takad',
            'lifafa':'lifaf',
            'rago':'rag',
            'gurgu':'gurg',
            'kano':'kan',
            'gudana':'gudan',
            'dorina':'dorin',
            'kirga':'kirg',
            'kwaya':'kway',
            'share':'shar',
            'girki':'girk',
            'takalmi':'takalm',
            'wanka':'wank',
            'wanki':'wank',
            'dukufa':'dukuf',
            'suma':'sum',
            'rame':'ram',
            'mallaka':'mallak',
            'wasika':'wasik',
            'jarida':'jarid',
            'gwano':'gwan',
            'gwanda':'gwan',
            'gyambo':'gyamb',
            'rauni':'raun',
            'kida':'kid',
            'rawa':'raw',
            'rangwada':'rangwad',
            'tuwo':'tuw',
            'masara':'masar',
            'masarauta':'masaraut',
            'makaranta':'makarant',
            'hankali':'hankal',
            'fasata':'fasat',
            'dangantaka':'dangantak',
            'aukuwa':'aukuw',
            'jarida':'jarid',
            'kifi':'kif',
            'rijiya':'rijiy',
            'wuri':'wur',
            'famfo':'famf',
            'yanka':'yank',
            'ashasha':'ashash',
            'dambe':'damb',
            'gama':'gam',
            'riba':'rib',
            'kwando':'kwand',
            'tallafi':'tallaf',
            'haihuwa':'haihuw',
            'damuwa':'damuw',
            'rabuwa':'rabuw',
            'takala':'takal',
            'rubutu':'rubut',
            'rubuta':'rubut',
            'rubutai':'rubut',
            'rubututtuka':'rubuttuk',
            'tsuntsuwa':'tsunts',
            'tsuntsaye':'tsunts',
            'alamar':'alam',
            'alamomin':'alam',
            'alamu':'alam',
            'alamun':'alam',
            'asibitin':'asibit',
            'musulmai':'musulm',
            'musulmi':'musulm',
            'musulma':'musulm',
            'sa"o"i' :'sa"a"',
            'shugabannin':'shugaban',
            'wayoyin':'wayoy',
            'kare':'kar',
            'kazanta':'kazant',
            'kazama':'kazam',
            'kunnai':'kun',
            'mummunan':'mummun',
            'sabuwar':'sabuw',
            'sabon':'sab',
            'sababbi':'sabab',
            'sabofil':'sabof',
            'sabuwa':'sabuw',
            'kashi':'kash',
            'guje-guje':'guj',
            'guduwa':'guduw',
            'madafai':'madaf',
            'marubuta':'rubut',
            'marubuciya':'rubuc',
            'mahaukaci':'hauk',
            'mahaukaciya':'hauk',
            'rubuce-rubuce':'rubuc',
            'abokai':'abok',
            'abokina':'abokin',
            'abokinsa':'abokin',
            'abokanansa':'abokan',
            'abokina':'abokin',
            'littattafai':'littaf',
            'bangarori':'bangaror',
            'bangaren':'bangar',
            'gidaje':'gidaj',
            'gidajen':'gidaj',
            'gidajensu':'gidaj',
            'gidan':'gid',
            'gidanka':'gidan',
            'gidansa':'gidan',
            'gidansu':'gidan',
            'ramuka':'ram',
            'mazaje':'mazaj',
            'yanmata':'yanmat',
            'huluna':'hulun',
            'makarantu':'karant',
            'amincin':'aminc',
            'shugabanmu':'shugaban',
            'ahlayensa':'iyal',
            'Kyawawan':'Kyauwaw',
            'ciki':'cik',
            'duniyarsu':'duniyar',
            'labarin':'labar',
            'kasashe':'kasash',
            'wautar':'waut',
            'kasarku':'kasark',
            'sarkinsu':'sark',
            'wazirinmu':'wazirin',
            'labarinsan':'labarin',
            'hakikance':'hakikanc',
            'wazirci':'wazirc',
            'dubbai':'dubb',
            'mulkinmu':'mulkin',
            'mulki':'mulk',
            'kadaici':'kadaic',
            'kawaici':'kawaic',
            'tagwaye':'tagway',
            'bambanci':'bambanc',
            'hallaci':'hallac',
            'mutuntaka':'mutuntak',
            'jahilci':'jahilc',
            'lafci':'lafc',
            'gajarta':'gajart',
            'samartaka':'samartak',
            'boranci':'boranc',
            'wawanci':'wawan',
            'gurgunta':'gurgun',
            'kumamanta':'kumaman',
            'abokanta':'abokan',
            'abokantaka':'abokan',
            'bauta':'bauta',
            'maita':'mait',
            'gabaci':'gabac',
            'kusanci':'kusanc',
            'lalaci':'lalac',
            'bakunci':'bakunc',
            'bokunta':'bakun',
            'gabunta':'gabun',
            'sabuntaka':'sabunt',
            'wofinta':'wofin',
            'gwaninta':'gwanin',
            'dolonci':'dolon',
            'gwarzantaka':'gwarzan',
            'shegantaka':'shegan',
            'gwamunta':'gwamun',
            'fatauci':'fatauc',
            'fatake':'fatak',
            'bajintaka':'bajin',
            'mahukunta':'hukun',
            'hukuma':'hukum',
            'karanta':'karan',
            'malami':'malam',
            'malanta':'malan',
            'azzalumi':'azzalum',
            'zalimu':'zalim',
            'munafiki':'munafik',
            'sharifi':'sharif',
            'amartaka':'amart',
            'budurci':'budur',
            'budurwa':'budur',
            'annabta':'annab',
            'samartaka':'samar',
            'yaranta':'yaran',
            'yara':'yar',
            'talaka':'talak',
            'matalauci':'talauc',
            'talakawa':'talakaw',
            'makauninya':'makaunin',
            'makaho':'makanta',
            'sirantaka':'sirant',
            'siriri':'sirir',
            'gwauranci':'gwauran',
            'gwaurantaka':'gwaurant',
            'bene':'ben',
            'bebenci':'beben',
            'danyantaka':'danyan',
            'hakimtaka':'hakimt',
            'hakimi':'hakim',
            'walitta':'walitt',
            'waliyi':'waliy',
            'waliya':'waliy',
            'bashi':'bash',
            'bauri':'baur',
            'daci':'dac',
            'danshi':'dansh',
            'dari':'dar',
            'fadi':'fad',
            'gautsi':'gauts',
            'kaifi':'kaif',
            'kanshi':'kansh',
            'karni':'karn',
            'kunci':'kun',
            'karfi':'karf',
            'kwari':'kwar',
            'lami':'lam',
            'laushi':'laush',
            'nauyi':'nauy',
            'santsi':'sants',
            'sanyi':'sany',
            'sauki':'sauk',
            'sauri':'saur',
            'tauri':'taur',
            'tsami':'tsam',
            'tsamiya':'tsamiy',
            'tsarki':'tsark',
            'wari':'war',
            'yauki':'yauk',
            'zafi':'zaf',
            'zaki':'zak',
            'zarni':'zarn',
            'zari':'zarn',
            'zartsi':'zarts',
            'zurfi':'zurf',
            'bazakiya':'bazak',
            'daci':'dac',
            'doyi':'doy',
            'muni':'mun',
            'tsini':'tsin',
            'wukake':'wukak',
            'dumi':'dum',
            'daci':'dac',
            'daci-daci':'dac',
            'kauri-kauri':'kaur',
            'bashi-bashi':'bash',
            'bauri-bauri':'baur',
            'danshi-danshi':'dansh',
            'daari-daari':'dar',
            'gautsi-gautsi':'gauts',
            'kaifi-kaifi':'kaif',
            'kanshi-kanshi':'kansh',
            'karni-karni':'karn',
            'karfi-karfi':'karf',
            'kwari-kwari':'kwar',
            'lami-lami':'lam',
            'laushi-laushi':'laush',
            'nauyi-nauyi':'nauy',
            'santsi-santsi':'sants',
            'sanyi-sanyi':'sany',
            'sauki-sauki':'sauk',
            'sauri-sauri':'saur',
            'tauri-tauri':'taur',
            'tsami-tsami':'tsam',
            'wari-wari':'war',
            'yauki-yauki':'yauk',
            'zafi-zafi':'zaf',
            'zaki-zaki':'zak',
            'zarni-zarni':'zarn',
            'zari-zari':'zar',
            'zartsi-zartsi':'zarts',
            'zurfi-zurfi':'zurf',
            'daci-daci':'dac',
            'doyi-doyi':'doy',
            'muni-muni':'mun',
            'tsini-tsini':'tsin',
            'dumi-dumi':'dum',
            'dumi-duminsa':'dumin',
            'faffada':'faffad',
            'zazzaka':'zzazz',
            'zuzzurfa':'zuzzurf',
            'fadada':'fadad',
            'zakaka':'zakak',
            'zurfafa':'zurfaf',
            'zazzafa':'zazzaf',
            'karfaffa':'karfaff',
            'gaggautsa':'gaggauts',
            'gautsatsa':'gautsats',
            'rarrauna':'rarraun',
            'raunana':'raunan',
            'sassantsa':'sassants',
            'santsatsa':'satsats',
            'zazzartsa':'zazzarts',
            'kyakkyawa':'kyakkyaw',
            'kyawawa':'kyawaw',
            'mummuna':'mummun',
            'munana':'munan',
            'girmama':'girm',
            'sirara':'sirar',
            'kausasa':'kausas',
            'saukaka':'sauk',
            'taurara':'taur',
            'tsarkaka':'tsark',
            'yausasa':'yausas',
            'zakaka':'zakak',
            'sauwaka':'sauwak',
            'saukake':'saukak',
            'dafaffe':'dadaff',
            'dafe-dafe':'daf',
            'cikakke':'cikak',
            'cikakkiya':'cikakk',
            'cikakku':'cikakk',
            'dafaffiya':'dafaff',
            'dafaffu':'dafaff',
            'gagararre':'gagararr',
            'gagararriya':'gagarr',
            'gagararru':'gagararr',
            'gasasshe':'gasash',
            'gasassu':'gasass',
            'gasasshiya':'gasassh',
            'satacce':'satac',
            'satacciya':'satac',
            'sataccu':'satac',
            'tsukakke':'tsukak',
            'tsukuku':'tsuk',
            'tsukkiya':'tsukk',
            'tsukakku':'tsukak',
            'yagalgalle':'yagalgal',
            'yagalgalliya':'yagalgal',
            'yagalgalallu':'yagalgalal',
            'matacce':'matac',
            'mutacciya':'mutac',
            'matattu':'matat',
            'gajiya':'gaj',
            'gajiyayye':'gajiyay',
            'gajiyayya':'gajiyay',
            'gajiyayyu':'gajiyay',
            'tafiya':'taf',
            'matafiyi':'tafiy',
            'matafiya':'tafiy',
            'tafiyayye':'tafiy',
            'tafiyayya':'tafiyay',
            'tafiyayya':'tafiyay',
            'ci':'ci',
            'ciyayye':'ciyay',
            'ciyayyu':'ciyay',
            'ciyayyiya':'ciyay',
            'ciyayyu':'ciyay',
            'lafiyayye':'lafiyay',
            'lafiyayya':'lafiyay',
            'lafiyayyu':'lafiyay',
            'masifaffiya':'masifaff',
            'masifaffe':'masifaf',
            'masifaffu':'masifaf',
            'wankakku':'wankak',
            'wankakke':'wankak',
            'wankakkiya':'wankakk',
            'motoci':'motoc',
            'kunsasshe':'kunsassh',
            'kunsasshiya':'kunsassh',
            'kunsasshu':'kunsassh',
            'yagawa':'yagaw',
            'yagaggiya':'yagagg',
            'yagaggu':'yagagg',
            'yagagge':'yagagg',
            'tababbe':'tabab',
            'tababbiya':'tababb',
            'tabbabu':'tabbab',
            'kwababbiya':'kwababb',
            'kwaba':'kwab',
            'kwababbi':'kwabab',
            'kwababbu':'kwabab',
            'marowaci':'row',
            'marowancin':'row',
            'bahaguwa':'hag',
            'bahago':'hag',
            'balo-balo':'bal',
            'ruwa-ruwa':'ruw',
            'ruku-ruku':'ruk',
            'gari-gari':'gar',
            'gudaji-gudaji':'gudaj',
            'hoto-hoto':'hot',
            'shiru-shiru':'shir',
            'tsakuwa-tsakuwa':'tsakuw',
            'yashi-yashi':'yash',
            'baki-baki':'bak',
            'fari-fari':'far',
            'dogo-dogo':'dog',
            'baka-baka':'bak',
            'doguwa-doguwa':'doguw',
            'daffafe-daffafe':'daffaf',
            'kakkaura':'kaur',
            'jaja-jaja':'ja',
            'bagidajiya-bagidajiya':'bagidaj',
            'bagidaje-bagidaje':'bagidaj',
            'santala-santala':'santal',
            'sanu-sanu':'san',
            'faufau':'fauf',
            'yanmata':'yanmat',
            'koyaya':'koyay',
            'bazar-bazar':'bazar',
            'cibiya':'cibiy',
            'zuciya':'zuciy',
            'hannaye':'hannay',
            'kunnuwa':'kunnuw',
            'asussuba':'asussub',
            'maza-maza':'maz',
            'marmaza':'marm',
            'mafadaci':'mafadac',
            'mafadaciya':'mafadac',
            'mafadata':'mafad',
            'mahaifi':'mahaif',
            'mahaifiya':'mahaif',
            'mahaifa':'mahaif',
            'maroki':'marok',
            'maroka':'marok',
            'marokiya':'marok',
            'matsoraci':'matsor',
            'matsoraciya':'matsorac',
            'matsorata':'matsor',
            'maboyi':'maboy',
            'mabiya':'biy',
            'maniyyaci':'niyy',
            'maniyata':'niyat',
            'makadaici':'makadaic',
            'makadaita':'makadait',
            'mahadddaci':'haddd',
            'mahaddaciya':'hadda',
            'mahaddata':'hadda',
            'masani':'san',
            'masana':'san',
            'masaniya':'saniy',
            'dagula':'dagul',
            'doke':'dok',
            'mare':'mar',
            'azabtar':'azabt',
            'amince':'aminc',
            'sari':'sara',
            'wanke':'wank',
            'wanke-wanke':'wank',
            'tsoratarwa':'tsoratarw',
            'dauru':'daur',
            'sukan':'suk',
            'zabi':'zab',
            'badin-badada':'badad',
            'kumbura':'kunbur',
            'gabace':'gab',
            'wulakantacce':'wulakantac',
            'wulakantaciya':'wulakantac',
            'bafaranshe':'faransh',
            'bafaranshiya':'faransh',
            'faransawa':'ransaw',
            'bahaushe':'haush',
            'bahaushiya':'haush',
            'hausawa':'hausaw',
            'bajamushe':'jamush',
            'bajamushiya':'jamush',
            'jamusawa':'jamusaw',
            'bamasine':'sin',
            'bamasiniya':'siniy',
            'sinawa':'sinaw',
            'bakano':'kan',
            'bakatsine':'katsi',
            'bakatsiniya':'katsi',
            'katsinawa':'katsin',
            'balarabe':'larab',
            'balarabiya':'larab',
            'larabawa':'larabaw',
            'bamisire':'misir',
            'bamisiriya':'misriy',
            'misirawa':'mistraw',
            'basakkwace':'sakkwac',
            'basakkwata':'sakkwa',
            'sakkwatawa':'sakkwataw',
            'bature':'tur',
            'baturiya':'tur',
            'turawa':'turai',
            'bayarabe':'yarab',
            'bayaraba':'yarab',
            'yarbawa':'yarbaw',
            'banufe':'nuf',
            'banufa':'nuf',
            'nufawa':'nuf',
            'bazamfare':'zamf',
            'bazanfara':'zamfar',
            'zanfarawa':'zanfaraw',
            'bamalike':'malik',
            'malikawa':'malik',
            'bamalikkiya':'malik',
            'bazawara':'bazawar',
            'zaurawa':'zaur',
            'zauranci':'zauranc',
            'badauri':'daur',
            'daurawa':'daur',
            'dadauriya':'daur',
            'bafillace':'fill',
            'bafillaciya':'fillac',
            'bafilatana':'filat',
            'fulani':'fulan',
            'gabasawa':'gabas',
            'gabashiya':'gabash',
            'gabasawa':'gabas',
            'bazazagi':'zazag',
            'zazzagawa':'zazzagaw',
            'bazazzagiya':'zazzagiy',
            'bazazzaga':'zazzag',
            'gobirawa':'gobir',
            'bagoburi':'bagobur',
            'bagidaje':'gidaj',
            'batijjane':'tijjan',
            'adamawa':'adamaw',
            'agadasawa':'gadasaw',
            'kasuwoyi':'kasuwoy',
            'gyare-gyaren':'gyar',
            'dakwalwa':'dakwalw',
            'cif-cif':'cif',
            'dar-dar':'dar',
            'kwal-kwal':'kwal',
            'hankalimmu':'hankalim',
            'karyace-karyace':'kary',
            'adaranci':'adaran',
            'yarbanci':'yarban',
            'hausanci':'haus',
            'barbanci':'barb',
            'duniyanci':'duniy',
            'fadanci':'fad',
            'filatanci':'filat',
            'ganganci':'gang',
            'kabilanci':'kabil',
            'malamanci':'malam',
            'kananci':'kan',
            'kudanci':'kud',
            'yammaci':'yamm',
            'gabashi':'gabash',
            'arewanci':'arew',
            'auratayya':'auratay',
            'fasinjoji':'fasinjoj',
            'harzuwa':'harzuw',
            'kaffafuwa':'kaffafuw',
            'mimmike':'mimmik',
            'kauna':'kaun',
            'yar-malam':'yar-malam',
            'dan-malam':'dan-malam',
            'zauna':'zaun',
            'maaikachi':'aikach',
            'mafauchi':'fauc',
            'marowachi':'row',
            'matsorachi':'tsorach',
            'miji':'Mij',
            'mutum':'Mutum',
            'namiji':'namij',
            'ango':'ango',
            'saurayi':'sauray',
            'Wa':'Wa',
            'bunsuru':'Bunsur',
            'rago':'Rag',
            'toro':'toro',
            'rakumi':'rakumi',
            'zakara':'zakara',
            'mata':'mat',
            'mache':'mach',
            'kwaya':'kwaya',
            'iri-iri':'iri',
            'Hainyaiyai':'hainy',
            'Dakunkuna':'dakunk',
            'Takardodi':'takard',
            'kudin':'kud',
            'babu':'bab',
            'abin':'ab',
            'agani':'gan',
            'kasa':'kas',
            'kasuwanci':'kasuw',
            'hanyoyi':'hanyoy',
            'komai':'kom',
            'cinhanci':'cinh',
            'rashawa':'rashaw',
            'Adu"ar':'adu"a',
            'haka':'hak',
            'kaci':'kac',
            'muku':'muk',
            'yawa':'yaw',
            'yanzu':'yanz',
            'kuna':'kun',
            'bayan':'bay',
            'wanda':'wand',
            'aka':'aka',
            'zalunta':'zalun',
            'kwayoyi':'kwayoy',
            'gado':'gad',
            'akusa':'akus',
            'fili':'fil',
            'filaye':'filay',
            'gainye':'gainy',
            'gainyaye':'gainyay',
            'gashi':'gash',
            'gasussuka':'gasussuk',
            'magunguna':'magungun',
            'chiye-chiye':'chiy',
            'day':'daya',
            'biyu':'biyu',
            'uku':'uku',
            'hudu':'hudu',
            'biyar':'biyar',
            'shidda':'shidda',
            'bakwai':'bakwai',
            'takwas':'takwas',
            'tara':'tara',
            'goma':'goma',
            'shadaya':'shadaya',
            'bara-gurbi':'bara-gurb',
            'baram-baram':'baram-baram',
            'dugunzuma':'dugunzum',
            'dugurguje':'dugurguj',
            'dumu-dumu':'dumu-dumu',
            'makamai':'makam',
            'fada':'fad',
            'filla-filla':'filla-filla',
            'gunguni':'gungun',
            'gunaguni':'gunagun',
            'turo':'tur', 
            'kofar':'kof',
            'dukansu':'dukans', 
            'suka':'suk',
            'mike':'mik',
            'wasu':'was',
            'mutane':'mutan',
            'kayan':'kay',
            'yakin':'yak',
            'jikin':'jik',
            'Malam':'malam', 
            'suka':'suka',
            'fara':'far',
            'dauka':'dauk',
            'daure':'daur',
            'masa':'mas',
            'hannu':'hann',
            'hada':'had',
            'icen':'ice',
            'likkafanin':'likkafan',
            'Ummanta':'umma',
            'shekarunsu':'shekaruns',
            'lokaci-lokaci':'likac',
            'dagargajew':'dagargajew',
            'shuke-shuken':'shuk',
            'murmushi':'murmush',
            'rayuwarta':'rayuw',
            'maganganu':'magan',
            'Mahaifinta':'haif',
            'haifa':'haif',
            'haramtacciyar':'haram',
            'gulmace-gulmacen':'gulm',
            'tsakaninsu':'tsakanins',
            'mummunan':'mummun',
            'tangamemen':'tangamemen',
            'lashe-lashensa':'lash',
            'tande-tande':'tande-tande',
            'harbe-harben':'harb',
            'ta"bara':'ta"bara',
            'lekawa':'lekaw',
            'barazanar':'barazan',
            'taimakeni':'taimak',
            'taimako':'taimak',





                
            
      # Add more words and their roots here
        }

        # Define lists of prefixes and suffixes
        self.prefixes = ["ma", "tsatt","yan", "mai", "ba", "ta", "abin", "wuri-n"]  
        self.suffixes = ["ai",'in','r', "ana","una", "ao", "ar", "awa", "aye", "cce", "che", "chi", "ci", "fa", "fen", "gu", "ilu", "ina", "ir", "ka", "ke", "ki", "ku", "mchi", "mci", "mtaka", "n", "nchi", "nci", "nda", "ni", " ake ","nka", "nku", "nna", "nni", "nnu", "nsa", "nsu", "nta", "ntka", "nu", "obi", "ochi", "odi", "ofi", "ogi", "oli", "ori", "oshi", "oti", "owa", "oyi", "rko", "ru", "sa", "shi", "suwa", "suwa","i","a","u","anci"]

    def stem(self, input_text):
        # Remove punctuation and split into words
        import re
        #words = re.findall(r'\b\w+\b', input_text)
        #words = re.findall(r'\b[A-Z][a-z]*\b|[.?]', input_text)
        words = re.findall(r'\b\w+\b|[.]', input_text)

        # Create an empty list to store stemmed words
        stemmed_words = []

        # Define stemming rules
        for word in words:
            # Check if the word is a stopword
            if word in self.stopwords:
                continue  # Skip stopwords

            # Apply stemming rules
            if word in self.dictionary:
                # If the word is in the dictionary, return it as is
                stemmed_words.append(self.dictionary[word])
            else:
                # Apply complex rules for prefixes and suffixes
                for prefix in self.prefixes:
                    if word.startswith(prefix):
                        word = word[len(prefix):]
                        break  # Only remove one prefix
                
                for suffix in self.suffixes:
                    if word.endswith(suffix):
                        word = word[:-len(suffix)]
                        break  # Only remove one suffix

                
                # Add the stemmed word to the list
                stemmed_words.append(word)
                
                 # Filter out words with a length of 1 after stemming
                stemmed_words = [word for word in stemmed_words if len(word) > 1]


        return ' '.join(stemmed_words)

# Example usage
if __name__ == "__main__":
    stemmer = HausaStemmer()
    input_text = "Jiya da na je gida sai naga gidaje kusan dari uku akusa da gidajen sarkin Kano. Abin mamaki shine gidajensu Malam Sabitu ma ashe suna, kusa da gidan sarkin da aka gina, gidanka dab da gidansa harda gidansu."
    stemmed_text = stemmer.stem(input_text)
    print("Input Text:\n", input_text, "\n")
    print("Stemmed Text:\n", stemmed_text)
    


# In[ ]:




